apiVersion: v1
kind: LimitRange
metadata:
  name: cinetrack-limits
  namespace: cinetrack
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      max:
        memory: 2Gi
        cpu: 2
