apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: catalog-db-credentials
  namespace: cinetrack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: catalog-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cinetrack/catalog-service/db
        property: username
    - secretKey: password
      remoteRef:
        key: cinetrack/catalog-service/db
        property: password
