apiVersion: v1
kind: Secret
metadata:
  name: cluster-prod-us
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    cinetrack/region: "true"
    env: prod-us
type: Opaque
stringData:
  name: prod-us
  server: https://prod-us-cluster.example.com
