apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: cinetrack
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: cinetrack
spec:
  selector:
    app.kubernetes.io/name: catalog-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
