apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: cinetrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/umur/cinetrack-catalog-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
