apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: cinetrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/umur/cinetrack-catalog-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport"
            # Kubernetes DNS: <service>.<namespace>.svc.cluster.local
            - name: SERVICES_USER_URL
              value: "http://user-service.cinetrack.svc.cluster.local:8081"
            - name: SERVICES_REVIEW_URL
              value: "http://review-service.cinetrack.svc.cluster.local:8082"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
