apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: cinetrack
data:
  application.properties: |
    spring.application.name=catalog-service
    server.port=8080
    tmdb.base-url=https://api.themoviedb.org/3
    tmdb.image-base-url=https://image.tmdb.org/t/p
    spring.cache.type=redis
    spring.data.redis.host=${REDIS_HOST:redis}
    spring.data.redis.port=${REDIS_PORT:6379}
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.probes.enabled=true
