apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinetrack-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cinetrack
  source:
    repoURL: https://github.com/umur/kubernetes-example
    targetRevision: main
    path: cinetrack-deploy/envs/dev/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
