apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-service-dev
  namespace: argocd
spec:
  project: cinetrack
  source:
    repoURL: https://github.com/umur/kubernetes-example
    targetRevision: main
    path: cinetrack-deploy/charts/catalog-service
    helm:
      valueFiles:
        - ../../envs/dev/values/catalog-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cinetrack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
