apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-service
  namespace: cinetrack
spec:
  minAvailable: 1      # always keep at least 1 pod running during voluntary disruptions
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
