apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watchlist-service-prod-eu
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cinetrack
    env: prod-eu
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cinetrack
  source:
    repoURL: https://github.com/umur/kubernetes-example
    targetRevision: main
    path: cinetrack-deploy/charts/watchlist-service
    helm:
      valueFiles:
        - ../../envs/prod-eu/values/watchlist-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cinetrack-prod-eu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
